### ISSUE TITLE
Need Help, mister NicoD (Please)

### ISSUE THREAD

**Issue by InfernalWolf666** [NicoD-SBC/armbian-gaming#11]
Hello my dear friend! I bought an orange pi 5 plus. And I came across you on YouTube. I'm watching you translated by a neural network.

Please tell me.

My original Wi-Fi and bluetooth Pcie device R6 adapter do not work in all unofficial images
http://www.orangepi.org/html/hardWare/computerAndMicrocontrollers/details/Orange-Pi-R6.html

This device works in official : Orange Pi OS (Arch and Droid) , Ubuntu. Debian !!!

Does not work on all other operating systems :(

**Comment by EvilOlaf** [comment]
No logs = impossible to diagnose

**Comment by InfernalWolf666** [comment]
Mister!
I'm a noob in the Linux world.
Please tell me where I can see the logs, I will provide them to you without any problems with great joy!

**Comment by InfernalWolf666** [comment]
Although I have a feeling that there is simply no necessary driver

**Comment by InfernalWolf666** [comment]
This guy has exactly the same error

https://forum.armbian.com/topic/29638-bluetoothwifi-not-working/

**Comment by NicoD-SBC** [comment]
Hi @InfernalWolf666 
This is not related to armbian-gaming. So I will close this issue. You can post on the Armbian forum about it and hope someone else can help.
This is an OrangePi product. A quick google doesn't show me any drivers for it available for Linux.
So you'll have to ask OrangePi for the drivers or try to get the driver out of their image.  Or check their github or so. 
Problem is they don't really communicate much with the community. And we don't have this hardware, so no way to test. I do have the OPi5+ but not this adapter.
I'd advice to use a supported wifi/bt USB adapter with Armbian until this is supported in mainline. 
Good luck.
