### ISSUE TITLE
Include PPSSPP dependency for Ubuntu 24.04

### ISSUE THREAD

**Issue by hqnicolas** [NicoD-SBC/armbian-gaming#16]
> sudo apt-get install libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev

this glu lib need to be included to fix the fatal error: GL/glu.h

Today I see: Armbian-gaming version 1.0 : For Armbian Jammy
and i'm trying to install on Noble

Armbian Gaming is an Great idea @NicoD-SBC

**Comment by NicoD-SBC** [comment]
Thank you, I added it to the ppsspp build. Will try later. Other stuff also doesn't work like wine64 on Noble.
If you know a fix, please let me know. Cheers.
