### ISSUE TITLE
These appear to be missing. I am running this on WSL

### ISSUE THREAD

**Issue by dvdvideo1234** [NicoD-SBC/armbian-gaming#3]
![image](https://user-images.githubusercontent.com/9112662/166913610-86b3a942-7928-4974-9fb0-9dccb2fc10bc.png)

**Comment by NicoD-SBC** [comment]
Focal is not supported. Only Jammy and Sid.

**Comment by dvdvideo1234** [comment]
Should I switch to another branch ?

**Comment by NicoD-SBC** [comment]
> Should I switch to another branch ?

Focal isn't supported anymore by Armbian. Now Jammy is the supported Ubuntu version. 
So I'd advice to switch to Jammy. But make a backup of your current image. You never know you want it back.
The script is also working on Armbian Sid. But that's a rolling release not supported by armbian. Just a nice way to check out newer software. Some things run better on it, some things don't.
