### ISSUE TITLE
Check for Libc6:armhf 

### ISSUE THREAD

**Issue by seanmikhaels** [NicoD-SBC/armbian-gaming#4]
Installing BOX86 completes successfully, however fails to run. Shows "could not find file box86 in bin folder even though it's there". Installing Libc6/libc6:armhf corrects the issues, however would like to see this as part of the script checks, or noted installation dependancies.

**Comment by NicoD-SBC** [comment]
It is in the script in the dependency list. No idea why it didn't install for you.

sudo apt -y install git cmake libncurses6:armhf **libc6:armhf** libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf libjpeg62:armhf  libudev1:armhf libgl1-mesa-dev:armhf  libx11-dev:armhf libsmpeg0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libsdl2-image-2.0-0:armhf libsdl2-mixer-2.0-0:armhf gcc-arm-linux-gnueabihf cmake git cabextract

**Comment by seanmikhaels** [comment]
> It is in the script in the dependency list. No idea why it didn't install for you.
> 
> sudo apt -y install git cmake libncurses6:armhf **libc6:armhf** libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libx11-dev:armhf libsmpeg0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libsdl2-image-2.0-0:armhf libsdl2-mixer-2.0-0:armhf gcc-arm-linux-gnueabihf cmake git cabextract

Would being on a 64bit system be the reason ?

**Comment by NicoD-SBC** [comment]
> Would being on a 64bit system be the reason ?

No. It is menth to work on arm64. I'm running it on Odroid N2+ without issue's. I did have to change a few things yesterday to make it work on the OPi800. 
So if you need it, download the latest version of the script. 
But this is a clusterf*ck with mixed architectures. Ptitseb is making a new program box32 that should solve this hell.

**Comment by seanmikhaels** [comment]
Thanks Agree, i tried to get BOX86 with Wine32 working on a 64bit install and just gave up. Wine64 also needs 32 bit x86 components in order to work which like you mentioned creates a dependency nightmare. ill give the new script a shot and report back. I was using it on Ubuntu Mate 22.04 btw. Thanks for the reply and hard work on this script
