### ISSUE TITLE
armbian-gaming.sh

### ISSUE THREAD

**Issue by LadyAlbedo** [NicoD-SBC/armbian-gaming#5]
I wasn't able to run armbian-gamimg.sh using $ sh armbian-gmaing.sh
I had to use $ chmod +x armbian-gaming.sh and then run it like any other executable file.

I'm not sure if this can be fixed when cloning the repo or not, but if it can be fixed it would be very helpful.  Other option is to just up the instructions so that it's known.

**Comment by NicoD-SBC** [comment]
Hi. The instructions are :
`/bin/bash ./armbian-gaming.sh (do not use sudo or root user)`

That works.
